version: '3.8'

services:
  mysqllocal:
    image: mysql
    environment:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    networks:
      - mysql-compose-network

      
networks: 
  mysql-compose-network:
    driver: bridge